<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Tarea3CRUD.Domain\Tarea3CRUD.Domain.csproj" />
    <ProjectReference Include="..\Tarea3CRUD.Infrastructure\Tarea3CRUD.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
